services:
  gallery-api:
    build: ./comfyui-gallery-server
    container_name: gallery-api
    ports:
      - "19321:5000"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped

  gallery-web:
    build: ./comfyui-gallery-web
    container_name: gallery-web
    ports:
      - "19320:80"
    depends_on:
      - gallery-api
    restart: unless-stopped
