// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QANgalleryServer.Data;

#nullable disable

namespace QANgalleryServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824145149_AddWorkAssets")]
    partial class AddWorkAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("QANgalleryServer.Models.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("QANgalleryServer.Models.CharacterTag", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CharacterTags");
                });

            modelBuilder.Entity("QANgalleryServer.Models.CharacterWork", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "WorkId");

                    b.HasIndex("WorkId");

                    b.ToTable("CharacterWorks");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Media", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Part", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("UserId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("QANgalleryServer.Models.PartTag", b =>
                {
                    b.Property<string>("PartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("PartId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PartTags");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UsageCount");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("QANgalleryServer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Work", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("QANgalleryServer.Models.WorkAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "SortOrder");

                    b.ToTable("WorkAssets");
                });

            modelBuilder.Entity("QANgalleryServer.Models.WorkPart", b =>
                {
                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartId")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("WorkParts");
                });

            modelBuilder.Entity("QANgalleryServer.Models.WorkTag", b =>
                {
                    b.Property<string>("WorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("WorkTags");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Character", b =>
                {
                    b.HasOne("QANgalleryServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QANgalleryServer.Models.CharacterTag", b =>
                {
                    b.HasOne("QANgalleryServer.Models.Character", "Character")
                        .WithMany("CharacterTags")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QANgalleryServer.Models.Tag", "Tag")
                        .WithMany("CharacterTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QANgalleryServer.Models.CharacterWork", b =>
                {
                    b.HasOne("QANgalleryServer.Models.Character", "Character")
                        .WithMany("CharacterWorks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QANgalleryServer.Models.Work", "Work")
                        .WithMany("CharacterWorks")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Media", b =>
                {
                    b.HasOne("QANgalleryServer.Models.Work", "Work")
                        .WithMany("MediaItems")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Part", b =>
                {
                    b.HasOne("QANgalleryServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QANgalleryServer.Models.PartTag", b =>
                {
                    b.HasOne("QANgalleryServer.Models.Part", "Part")
                        .WithMany("PartTags")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QANgalleryServer.Models.Tag", "Tag")
                        .WithMany("PartTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Work", b =>
                {
                    b.HasOne("QANgalleryServer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QANgalleryServer.Models.WorkAsset", b =>
                {
                    b.HasOne("QANgalleryServer.Models.Work", "Work")
                        .WithMany("Assets")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("QANgalleryServer.Models.WorkPart", b =>
                {
                    b.HasOne("QANgalleryServer.Models.Part", "Part")
                        .WithMany("WorkParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QANgalleryServer.Models.Work", "Work")
                        .WithMany("WorkParts")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("QANgalleryServer.Models.WorkTag", b =>
                {
                    b.HasOne("QANgalleryServer.Models.Tag", "Tag")
                        .WithMany("WorkTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QANgalleryServer.Models.Work", "Work")
                        .WithMany("WorkTags")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Character", b =>
                {
                    b.Navigation("CharacterTags");

                    b.Navigation("CharacterWorks");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Part", b =>
                {
                    b.Navigation("PartTags");

                    b.Navigation("WorkParts");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Tag", b =>
                {
                    b.Navigation("CharacterTags");

                    b.Navigation("PartTags");

                    b.Navigation("WorkTags");
                });

            modelBuilder.Entity("QANgalleryServer.Models.Work", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("CharacterWorks");

                    b.Navigation("MediaItems");

                    b.Navigation("WorkParts");

                    b.Navigation("WorkTags");
                });
#pragma warning restore 612, 618
        }
    }
}
